// <auto-generated />
namespace HospMgmt.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addfnamefield : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addfnamefield));
        
        string IMigrationMetadata.Id
        {
            get { return "201710271623138_addfnamefield"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
